// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskFlow.DataAccess;

#nullable disable

namespace TaskFlow.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250818082129_ReplaceTaskHistoryWithAuditLog")]
    partial class ReplaceTaskHistoryWithAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TaskFlow.Core.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OfficeName")
                        .IsUnique();

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 154, DateTimeKind.Utc).AddTicks(586),
                            OfficeName = "Office1",
                            UpdatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 154, DateTimeKind.Utc).AddTicks(1075)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 154, DateTimeKind.Utc).AddTicks(1520),
                            OfficeName = "Office2",
                            UpdatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 154, DateTimeKind.Utc).AddTicks(1521)
                        });
                });

            modelBuilder.Entity("TaskFlow.Core.Models.TaskAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedPart")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("TaskAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedPart = "Backend setup",
                            AssignedTo = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 910, DateTimeKind.Utc).AddTicks(332),
                            DueDate = new DateTime(2025, 8, 23, 8, 21, 24, 909, DateTimeKind.Utc).AddTicks(9844),
                            Status = "InProgress",
                            UpdatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 910, DateTimeKind.Utc).AddTicks(333),
                            WorkTaskId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedPart = "Frontend implementation",
                            AssignedTo = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 910, DateTimeKind.Utc).AddTicks(346),
                            DueDate = new DateTime(2025, 9, 2, 8, 21, 24, 910, DateTimeKind.Utc).AddTicks(343),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 910, DateTimeKind.Utc).AddTicks(347),
                            WorkTaskId = 2
                        });
                });

            modelBuilder.Entity("TaskFlow.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 560, DateTimeKind.Utc).AddTicks(3725),
                            EmployeeID = "123456",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            OfficeId = 1,
                            PasswordHash = "$2a$11$zfPL5d/blN8EMDzEnVaS2eZKvxQ02yvg.y1vRA/RVdcz4zJeu0NLi",
                            Title = "DepartmentHead",
                            UpdatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 560, DateTimeKind.Utc).AddTicks(3740)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 908, DateTimeKind.Utc).AddTicks(3217),
                            EmployeeID = "654321",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Smith",
                            OfficeId = 2,
                            PasswordHash = "$2a$11$QdvCxidMVpPqLTj/Vfgd.OzIXDnzM/2PvT8.oxOcKBGiIGUWLJf2m",
                            Title = "Staff",
                            UpdatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 908, DateTimeKind.Utc).AddTicks(3231)
                        });
                });

            modelBuilder.Entity("TaskFlow.Core.Models.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedBy = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 909, DateTimeKind.Utc).AddTicks(6209),
                            CurrentStatus = "Assigned",
                            Description = "Setup the initial project structure and repositories.",
                            DueDate = new DateTime(2025, 8, 28, 8, 21, 24, 909, DateTimeKind.Utc).AddTicks(1620),
                            IsArchived = false,
                            Priority = "High",
                            TaskTitle = "Initial Project Setup",
                            UpdatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 909, DateTimeKind.Utc).AddTicks(6213)
                        },
                        new
                        {
                            Id = 2,
                            AssignedBy = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 909, DateTimeKind.Utc).AddTicks(6264),
                            CurrentStatus = "InProgress",
                            Description = "Implement user login and registration functionality.",
                            DueDate = new DateTime(2025, 9, 7, 8, 21, 24, 909, DateTimeKind.Utc).AddTicks(6231),
                            IsArchived = false,
                            Priority = "Medium",
                            TaskTitle = "Develop User Authentication",
                            UpdatedAt = new DateTime(2025, 8, 18, 8, 21, 24, 909, DateTimeKind.Utc).AddTicks(6266)
                        });
                });

            modelBuilder.Entity("TaskFlow.Core.Models.TaskAssignment", b =>
                {
                    b.HasOne("TaskFlow.Core.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TaskFlow.Core.Models.WorkTask", "WorkTask")
                        .WithMany("Assignments")
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("TaskFlow.Core.Models.User", b =>
                {
                    b.HasOne("TaskFlow.Core.Models.Office", "Office")
                        .WithMany("Users")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("TaskFlow.Core.Models.WorkTask", b =>
                {
                    b.HasOne("TaskFlow.Core.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");
                });

            modelBuilder.Entity("TaskFlow.Core.Models.Office", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskFlow.Core.Models.WorkTask", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
